version: 0.0
os: linux
files:
  - source: /target/shipwreck-app-1.0-SNAPSHOT.war
    destination: /usr/share/tomcat7/webapps/
hooks:
  AfterInstall:
    - location: codedeploy/restartTomcat.sh
      timeout: 300
      runas: root